### ISSUE TITLE
URL adress - problem

### ISSUE THREAD

**Issue by AlexMcArrow** [iRessources/AgileDwarf#16]
in: http://redmine.tld/redmine/adtasks/list?project_id=test
link in task: http://redmine.tld/issues/2 !!! (/redmine/ - missed)

Redmine def-url = http://redmine.tld/redmine/

**Comment by ghost** [comment]
I  tried Agile dwarf today. The installation was very smooth. 

But then I also ran into the same above problem because I am running the redmine as a suburl.
Also the  drag & drop doesn't work in the Sprint tab because of this link problem. 

I tried some trials by playing with the java scripts used for getUrl. But no success until now.
Regards,

**Comment by markablov** [comment]
Fixed by 832dee70525f777ad2b3ba44883966060f9a4cea

**Comment by lfagundes** [comment]
After this commit my "Sprints" tab doesn't work anymore, it gives me a "Page not found" message.

Environment:
  Redmine version                          2.0.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.3
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  AgileDwarf                               0.0.3
  redmine_code_review                      0.5.0
  redmine_plugin_views_revisions           0.0.1
  redmine_smart_issues_sort                0.3.1
